### ISSUE TITLE
Comment modules interferes with Settings

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-Comment#5]
The new version for 4.0 of the Comment module seems too work good. But, when I turn on the Comment module the Omeka S Admin Settings are not available anymore, throws an error:
```
Laminas\Form\Exception\InvalidElementException: No element by the name of [comment] found in form in /xx/omeka-s-4.0.0/vendor/laminas/laminas-form/src/Fieldset.php:207
Stack trace:
#0 /xx/omeka-s-modules-4/Comment/Module.php(373): Laminas\Form\Fieldset->get()
#1 /xx/omeka-s-4.0.0/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Comment\Module->handleMainSettings()
#2 /xx/omeka-s-4.0.0/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#3 /xx/omeka-s-4.0.0/application/src/Form/SettingForm.php(394): Laminas\EventManager\EventManager->triggerEvent()
#4 /xx/omeka-s-4.0.0/vendor/laminas/laminas-form/src/FormElementManager.php(233): Omeka\Form\SettingForm->init()
#5 /xx/omeka-s-4.0.0/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(630): Laminas\Form\FormElementManager->callElementInit()
#6 /xx/omeka-s-4.0.0/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#7 /xx/omeka-s-4.0.0/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(171): Laminas\ServiceManager\ServiceManager->get()
#8 /xx/omeka-s-4.0.0/vendor/laminas/laminas-form/src/FormElementManager.php(336): Laminas\ServiceManager\AbstractPluginManager->get()
#9 /xx/omeka-s-4.0.0/application/src/Mvc/Controller/Plugin/GetForm.php(33): Laminas\Form\FormElementManager->get()
#10 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke()
#11 /xx/omeka-s-4.0.0/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(275): call_user_func_array()
#12 /xx/omeka-s-4.0.0/application/src/Controller/Admin/SettingController.php(12): Laminas\Mvc\Controller\AbstractController->__call()
#13 /xx/omeka-s-4.0.0/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\SettingController->browseAction()
#14 /xx/omeka-s-4.0.0/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#15 /xx/omeka-s-4.0.0/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#16 /xx/omeka-s-4.0.0/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#17 /xx/omeka-s-4.0.0/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#18 /xx/omeka-s-4.0.0/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#19 /xx/omeka-s-4.0.0/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#20 /xx/omeka-s-4.0.0/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#21 /xx/omeka-s-4.0.0/index.php(21): Laminas\Mvc\Application->run()
#22 {main}
```
When I disable the Comment module, the admin/setting page is OK again.

Omeka S v 4.0.0
Comment Module v 3.4.1.12

**Comment by allanaaa** [comment]
+1, on Omeka S 4.0.2

**Comment by rschwab** [comment]
You can fix this by editting Module.php and removing line 373: `->get('comment')`

I tried pasting a patch file here but it wouldn't take. Here's the text of the patch:
```
diff --git a/Module.php b/Module.php
index cf33afa..d59e097 100644
--- a/Module.php
+++ b/Module.php
@@ -370,7 +370,6 @@ class Module extends AbstractModule
 
         $event
             ->getTarget()
-            ->get('comment')
             ->get('comment_public_notify_post')
             ->setValue(implode("\n", $value));
     }
```

**Comment by rschwab** [comment]
BTW I tested the function and it still performs as intended by updating the "Notify public comments by email" setting.
